defaults: &defaults
  mapper:
    metadata_mapping: datacite_geoblacklight

test:
  <<: *defaults
  index:
    adapter: Solr
    url: http://uc3-dash2solr-dev.cdlib.org:8983/solr/geoblacklight
    open_timeout: 120          # connection open timeout in seconds
    read_timeout: 300          # read timeout in seconds
    retry_503: 3               # max retries
    retry_after_limit: 20      # retry wait time in seconds
  source:
    protocol: OAI
    oai_base_url: http://uc3-mrtoai-dev.cdlib.org:37001/mrtoai/oai/v2
    metadata_prefix: stash_wrapper
    seconds_granularity: true
  db:
    adapter: sqlite3
    database: ':memory:'
    pool: 5
    timeout: 5000
  update_uri: https://localhost:3000/stash/dataset

development:
  <<: *defaults
  index:
    adapter: Solr
    url: http://uc3-dash2solr-dev.cdlib.org:8983/solr/geoblacklight
    open_timeout: 120          # connection open timeout in seconds
    read_timeout: 300          # read timeout in seconds
    retry_503: 3               # max retries
    retry_after_limit: 20      # retry wait time in seconds
  source:
    protocol: OAI
    oai_base_url: http://uc3-mrtoai-stg.cdlib.org:37001/mrtoai/oai/v2
    metadata_prefix: stash_wrapper
    seconds_granularity: true
    set: cdl_dashdev
  db:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
  update_uri: https://dash-dev.ucop.edu/stash/dataset

stage:
  <<: *defaults
  index:
    adapter: Solr
    url: http://uc3-dash2solr-stg.cdlib.org:8983/solr/geoblacklight
    open_timeout: 120          # connection open timeout in seconds
    read_timeout: 300          # read timeout in seconds
    retry_503: 3               # max retries
    retry_after_limit: 20      # retry wait time in seconds
  source:
    protocol: OAI
    oai_base_url: http://uc3-mrtoai-stg.cdlib.org:37001/mrtoai/oai/v2
    metadata_prefix: stash_wrapper
    seconds_granularity: true
    sets:
      - dataone_dash
      - lbnl_dash
      - ucb_dash
      - ucd_dash
      - uci_dash
      - ucm_dash
      - ucop_dash
      - ucr_dash
      - ucsc_dash
      - ucsf_datashare_submitter
      - ucpress_dash
      - ucsb_dash
      - ocdp_dash
      - ucsb_dash
  db:
    adapter: sqlite3
    database: db/stage.sqlite3
    pool: 5
  update_uri: https://dash-stg.ucop.edu/stash/dataset

demo:
  <<: *defaults
  index:
    adapter: Solr
    url: http://uc3-dashdemo-stg.cdlib.org:8983/solr/geoblacklight
    open_timeout: 120          # connection open timeout in seconds
    read_timeout: 300          # read timeout in seconds
    retry_503: 3               # max retries
    retry_after_limit: 20      # retry wait time in seconds
  source:
    protocol: OAI
    oai_base_url: http://uc3-mrtoai-stg.cdlib.org:37001/mrtoai/oai/v2
    metadata_prefix: stash_wrapper
    seconds_granularity: true
    set: cdl_dash_demo
  db:
    adapter: sqlite3
    database: db/demo.sqlite3
    pool: 5
  update_uri: https://dashdemo.ucop.edu/stash/dataset

production:
  <<: *defaults
  index:
    adapter: Solr
    url: http://uc3-dash2solr-prd.cdlib.org:8983/solr/geoblacklight
    open_timeout: 120          # connection open timeout in seconds
    read_timeout: 300          # read timeout in seconds
    retry_503: 3               # max retries
    retry_after_limit: 20      # retry wait time in seconds
  source:
    protocol: OAI
    oai_base_url: http://uc3-mrtoai-prd.cdlib.org:37001/mrtoai/oai/v2
    metadata_prefix: stash_wrapper
    seconds_granularity: true
  db:
    adapter: sqlite3
    database: db/production.sqlite3
    pool: 5
  update_uri: https://dash.ucop.edu/stash/dataset

